[package]
name = "teamswordphin/shapecasthitbox"
description = "A shapecast-centric solution to melee hitboxes. Successor to RaycastHitbox."
version = "0.2.4"
license = "MIT"
authors = ["TeamSwordphin", "colbert2677"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]